### ISSUE TITLE
다른 아이디어 가져오기

### ISSUE THREAD

**Issue by yeyey-y** [YAPP-16th/Team_Android_2_Client#10]

**Comment by LeeOhHyung** [comment]
음성편지, 잉여자원, 소모품관리 3개 이외에도 더 괜찮은 아이디어가 있으면 논의 해보는거죠??

**Comment by yeyey-y** [comment]
네 논의는 올릴수 있습니다. 하지만 19일(수요일)후부터 아이디어를 더 가져오는 건 일정 상 어려울 것 같아요
