### ISSUE TITLE
[Android] 프로젝트 셋팅 및 라이브러리 설정

### ISSUE THREAD

**Issue by chlalstjd430** [YAPP-16th/Team_Android_2_Client#17]
### 요약
- 프로젝트 셋팅 및 라이브러리 설정
- Retrofit으로 Backend API 연결만 해보기
- Git-Flow 를 위한 Branch설정 및 PR/ISSUE Template 등록
- CleanArchitecture, MVVM, MVP 레퍼런스 전달

**Comment by LeeOhHyung** [comment]
해당 [PR](https://github.com/YAPP-16th/Team_Android_2_Client/pull/16)에서 Merge 하였습니다.
